"""Fluxos novos contra instância de teste; INTEGRA_TEST_URL deve apontar a base descartável."""
import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

ROOT=Path(__file__).resolve().parent.parent
URL=os.environ.get('INTEGRA_TEST_URL','http://127.0.0.1:8081')

with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    context=browser.new_context(viewport={'width':1440,'height':1000})
    page=context.new_page();errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(URL)
    page.locator('#demo-access').click()
    page.get_by_role('heading',name='Painel da rede',exact=True).wait_for()
    token=page.evaluate('state.csrf')
    def post(path,data):
        r=context.request.post(URL+'/api'+path,data=data,headers={'X-CSRF-Token':token})
        assert r.ok,(r.status,r.text())
        return r.json()
    def goto(module):
        page.evaluate('(m)=>location.hash=m',module)
        page.wait_for_function('(m)=>state.route===m&&!document.querySelector("#main .loading-screen")',arg=module)
        assert 'Não foi possível carregar' not in page.locator('#main').inner_text(),module
    modules=list(context.request.get(URL+'/api/meta').json()['modules'])
    for module in modules:
        goto(module)
        page.locator('#new-record').click()
        page.locator('#record-form').wait_for()
        page.locator('#close-modal').click()
    goto('encounters');page.locator('#new-record').click()
    form=page.locator('#record-form')
    form.locator('[name=patient_id]').select_option('1')
    form.locator('[name=unit_id]').select_option('1')
    form.locator('[name=care_type]').select_option('Odontologia')
    expect(form.locator('.odontogram')).to_be_visible()
    form.locator('[data-tooth="11"]').select_option('Cárie')
    for name in ('subjective','objective','assessment','plan','dental_plan'):
        form.locator('[name='+name+']').fill('Registro de teste no navegador')
    form.locator('[type=submit]').click()
    expect(page.locator('#modal')).not_to_be_visible()
    page.locator('.record-open').first.click()
    expect(page.locator('[data-tooth="11"]')).to_have_value('Cárie')
    page.locator('#attachment-form input').set_input_files({'name':'documento.pdf','mimeType':'application/pdf','buffer':b'%PDF-1.4\nDocumento demonstrativo'})
    page.locator('#attachment-form button').click()
    expect(page.locator('.attachment-list')).to_contain_text('documento.pdf')
    page.locator('#record-form [name=status]').select_option('Finalizado')
    page.locator('#record-form [type=submit]').click()
    expect(page.locator('#modal')).not_to_be_visible()
    page.locator('.record-open').first.click()
    expect(page.locator('#record-tools')).to_contain_text('Integridade do documento verificada')
    expect(page.locator('#record-form [name=plan]')).to_be_disabled()
    page.locator('#print-record').click()
    expect(page.locator('.print-report')).to_contain_text('11: Cárie')
    page.screenshot(path=str(ROOT/'artifacts/relatorio-clinico.png'),full_page=True,animations='disabled')
    page.locator('#close-modal').click()
    asset=post('/records/assets',dict(unit_id=1,name='Equipamento teste UI',tag='UI-001',responsible='Equipe',acquisition_date='2025-01-01',value=1200,useful_life=12,residual_value=0))
    goto('assets');page.locator('.record-open').first.click();page.locator('#asset-event').click()
    page.locator('[name=kind]').select_option('Inventário')
    page.locator('[name=condition]').select_option('Localizado')
    page.locator('[name=notes]').fill('Conferência no navegador')
    page.locator('#asset-form [type=submit]').click();expect(page.locator('#modal')).not_to_be_visible()
    goto('compliance')
    expect(page.locator('.compliance-external')).to_have_count(32)
    expect(page.locator('.compliance-local')).to_have_count(38)
    red=page.locator('.compliance-external').first.evaluate('(el)=>getComputedStyle(el).backgroundColor')
    assert red=='rgb(255, 241, 242)',red
    page.screenshot(path=str(ROOT/'artifacts/aderencia-auditada.png'),full_page=False,animations='disabled')
    page.locator('#compliance-filter').select_option('external')
    expect(page.locator('.compliance-local')).to_have_count(0)
    page.locator('#compliance-search').fill('SISAB')
    expect(page.locator('#compliance-rows tr')).to_have_count(1)
    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.screenshot(path=str(ROOT/'artifacts/aderencia-mobile.png'),full_page=True,animations='disabled')
    goto('reports')
    expect(page.locator('#analytics-filter')).to_be_visible()
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.screenshot(path=str(ROOT/'artifacts/indicadores-mobile.png'),full_page=True,animations='disabled')
    goto('migration');expect(page.locator('#record-migration')).to_be_visible()
    payload=dict(source='Navegador teste',items=[dict(source_id='ui1',module='support',data=dict(subject='Importado UI',category='Suporte',priority='Normal',description='Registro de teste'))])
    page.locator('#record-import-form input').set_input_files({'name':'dados.json','mimeType':'application/json','buffer':json.dumps(payload).encode()})
    page.locator('#record-import-form [type=submit]').click()
    expect(page.locator('#record-import')).to_be_enabled()
    page.locator('#record-import').click()
    expect(page.locator('#record-import-result')).to_contain_text('1 registros importados')
    goto('users')
    page.locator('.identify-professional').first.click()
    page.locator('[name=professional_cpf]').fill('52998224725')
    page.locator('#identify-form [type=submit]').click()
    expect(page.locator('#modal')).not_to_be_visible()
    expect(page.locator('#main')).to_contain_text('CPF vinculado')
    page.locator('#new-user').click()
    expect(page.locator('[name=professional_cpf]')).to_be_visible()
    page.locator('#close-modal').click()
    citizen_context=browser.new_context(viewport={'width':390,'height':844})
    citizen=citizen_context.new_page();citizen.on('pageerror',lambda e:errors.append(str(e)))
    citizen.goto(URL+'/cidadao');citizen.locator('#demo-access').click()
    citizen.get_by_role('heading',name='Olá, Maria.').wait_for()
    post('/records/messages',dict(patient_id=1,subject='Atualização instantânea UI',body='Mensagem de teste restrita à instância temporária'))
    expect(citizen.get_by_role('heading',name='Atualização instantânea UI')).to_be_visible(timeout=8000)
    post('/records/messages',dict(patient_id=2,subject='Mensagem privada de outro titular',body='Não pode aparecer'))
    expect(citizen.get_by_role('heading',name='Mensagem privada de outro titular')).to_have_count(0)
    citizen.screenshot(path=str(ROOT/'artifacts/cidadao-tempo-real.png'),full_page=True,animations='disabled')
    citizen.wait_for_function('navigator.serviceWorker.controller!==null')
    cache_urls=citizen.evaluate('async()=>{const result=[];for(const name of await caches.keys()){const c=await caches.open(name);result.push(...(await c.keys()).map(r=>r.url));}return result;}')
    assert not any('/api/' in u for u in cache_urls),cache_urls
    assert all(u.endswith(('/static/offline.html','/static/icon.svg')) for u in cache_urls)
    citizen_context.set_offline(True);citizen.goto(URL+'/cidadao')
    expect(citizen.get_by_role('heading',name='Você está sem conexão')).to_be_visible()
    assert not errors,errors
    print(f'OK: {len(modules)} módulos, odontograma, anexos, finalização, relatório, inventário, aderência vermelha, BI, migração, mensagens em tempo real, isolamento e PWA offline.')
    browser.close()
